DELETE http://localhost:3003/api/blogs/60c5f77a2ab64c04f8ae4458
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphMSIsImlkIjoiNjBiZTQyYjAyZjk5NjIwNWIwNjZiN2MzIiwiaWF0IjoxNjIzMjYzMDE0fQ.1xWeM7HHiQ4M0MbKd0ZuW-AaiTr7MwC-O9ywWpGMufo

{
    "title": "Mikki Hiiren seikkailut5",
    "author": "Walt Disney5",
    "url": "www.mikkidisney.com5",
    "likes": "135",
    "userId": "60be42b02f996205b066b7c3"
}