DELETE http://localhost:3003/api/blogs/60c107a112c969028ce40d6c
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhYWphMSIsImlkIjoiNjBiZTQyYjAyZjk5NjIwNWIwNjZiN2MzIiwiaWF0IjoxNjIzMjYzMDE0fQ.1xWeM7HHiQ4M0MbKd0ZuW-AaiTr7MwC-O9ywWpGMufo

{
    "title": "Mikki Hiiren seikkailut2",
    "author": "Walt Disney2",
    "url": "www.mikkidisney.com2",
    "likes": "113",
    "userId": "60be42b02f996205b066b7c3"
}